### ISSUE TITLE
Eror while invoking .skyc exporter on the Skybrush Studio Server

### ISSUE THREAD

**Issue by aiankitp** [skybrush-io/studio-blender#27]
This time I am not able to export .skyc files from blender. but previously I was. But that time also I was facing different issue that my files were working fine in blender and skybrush viewer also. But when I was trying to upload show data on skybrush live, that time the files was working on only for virtual.jsonc server not for outdoor.

**Comment by ntamas** [comment]
Sorry, we can't really know what's wrong without seeing your files. Please contact us on [Discord](https://skybrush.io/r/discord) and report your issue there in the #issues or #studio channel, and post the problematic files there.
