### ISSUE TITLE
Blender 4.0

### ISSUE THREAD

**Issue by thealetree** [skybrush-io/studio-blender#9]
The HUD for speed and min distance no longer displayed in Blender 4.0, though the rest of the addon seems to  be functioning.

**Comment by ntamas** [comment]
Thanks for the feedback, we'll look into this shortly!

**Comment by ntamas** [comment]
Most likely cause for the original bug report is [this](https://projects.blender.org/blender/blender/issues/114359).

As for the error message in your second comment, this seems to be an incorrect installation of the plugin. Most likely installing a new version over an older one does not work smoothly. Try removing our add-on completely and then re-installing it from the ZIP downloaded from our homepage.

**Comment by ntamas** [comment]
No, actually, there's more to the story of the original bug report:

```
Traceback (most recent call last):
  File "/Users/tamas/Library/Application Support/Blender/4.0/scripts/addons/vendor/skybrush/sbstudio/plugin/overlays/safety_check.py", line 100, in draw_2d
    blf.size(font_id, int(11 * ui_scale), 72)
TypeError: blf.size() takes exactly 2 arguments (3 given)
```

**Comment by thealetree** [comment]
> Most likely cause for the original bug report is [this](https://projects.blender.org/blender/blender/issues/114359).
> 
> As for the error message in your second comment, this seems to be an incorrect installation of the plugin. Most likely installing a new version over an older one does not work smoothly. Try removing our add-on completely and then re-installing it from the ZIP downloaded from our homepage.

Thanks, I now have the updated version installed successfully. 

I'll continue to use Blender 3.6.5LTS for now though. Not sure how to resolve the issue with the links provided (does sky brush code need to be updated to accommodate for the deprecation?).

Thanks very much for the super speedy reply btw!

**Comment by ntamas** [comment]
HUD is now fixed in fe1b9b0. I'll wait a few days to see if there are more reports about issues with Blender 4, and if there aren't any, I'll release a new patch version.

Until then, you can take a look at the changes in fe1b9b0 and apply these in the source code of the plugin on your machine.

**Comment by ntamas** [comment]
Version 3.0.2 of the plugin is now released and it should support Blender 4 out of the box. Let us know if something is not working correctly.

**Comment by thealetree** [comment]
Hey thanks so much! Seems like it's working great for me 👍
